CREATE TABLE IF NOT EXISTS BOOKING (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    service_type VARCHAR(255) NOT NULL,
    date DATE NOT NULL
);

-- src/main/resources/schema.sql

CREATE SEQUENCE IF NOT EXISTS BOOKING_SEQ START WITH 1 INCREMENT BY 1;
